services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $apiSecretKey: '%sfs_subscription.adapter.stripe.apiSecretKey%'
            $webhookSigningSecret: '%sfs_subscription.adapter.stripe.webhookSigningSecret%'

    Softspring\SubscriptionBundle\Adapter\CustomerAdapterInterface:
        class: Softspring\SubscriptionBundle\Adapter\Stripe\StripeCustomerAdapter

    Softspring\SubscriptionBundle\Adapter\NotifyAdapterInterface:
        class: Softspring\SubscriptionBundle\Adapter\Stripe\StripeNotifyAdapter

    Softspring\SubscriptionBundle\Adapter\SubscriptionAdapterInterface:
        class: Softspring\SubscriptionBundle\Adapter\Stripe\StripeSubscriptionAdapter

    Softspring\SubscriptionBundle\Adapter\PlanAdapterInterface:
        class: Softspring\SubscriptionBundle\Adapter\Stripe\StripePlanAdapter

    Softspring\SubscriptionBundle\Adapter\SourceAdapterInterface:
        class: Softspring\SubscriptionBundle\Adapter\Stripe\StripeSourceAdapter

    Softspring\SubscriptionBundle\EventListener\StripeSubscriptionListener:
        tags: ['kernel.event_subscriber']

    Softspring\SubscriptionBundle\EventListener\StripeNotifyListener:
        tags: ['kernel.event_subscriber']

    Softspring\SubscriptionBundle\EventListener\StripeAdminSubscriptionListener:
        tags: ['kernel.event_subscriber']