services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $apiSecretKey: '%sfs_customer.adapter.stripe.apiSecretKey%'
            $webhookSigningSecret: '%sfs_customer.adapter.stripe.webhookSigningSecret%'
            $logger: '@?monolog.logger.stripe'

    Softspring\SubscriptionBundle\Platform\Adapter\SubscriptionAdapterInterface:
        class: Softspring\SubscriptionBundle\Platform\Adapter\Stripe\SubscriptionAdapter
        tags:
          - { name: 'sfs_customer.platform.adapter', alias: 'subscription' }

    Softspring\SubscriptionBundle\Platform\Adapter\PlanAdapterInterface:
        class: Softspring\SubscriptionBundle\Platform\Adapter\Stripe\PlanAdapter
        tags:
          - { name: 'sfs_customer.platform.adapter', alias: 'plan' }

    Softspring\SubscriptionBundle\Platform\Adapter\ProductAdapterInterface:
        class: Softspring\SubscriptionBundle\Platform\Adapter\Stripe\ProductAdapter
        tags:
          - { name: 'sfs_customer.platform.adapter', alias: 'product' }

    Softspring\SubscriptionBundle\EventListener\StripeSubscriptionListener:
        tags: ['kernel.event_subscriber']

    Softspring\SubscriptionBundle\EventListener\StripeSubscriptionsNotifyListener:
        tags: ['kernel.event_subscriber']

    Softspring\SubscriptionBundle\EventListener\StripeAdminSubscriptionListener:
        tags: ['kernel.event_subscriber']