services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $apiSecretKey: '%sfs_subscription.adapter.stripe.apiSecretKey%'

    Softspring\SubscriptionBundle\Adapter\ClientAdapterInterface:
        class: Softspring\SubscriptionBundle\Adapter\Stripe\StripeClientAdapter

    Softspring\SubscriptionBundle\Adapter\SubscriptionAdapterInterface:
        class: Softspring\SubscriptionBundle\Adapter\Stripe\StripeSubscriptionAdapter

    Softspring\SubscriptionBundle\Adapter\PlanAdapterInterface:
        class: Softspring\SubscriptionBundle\Adapter\Stripe\StripePlanAdapter

    Softspring\SubscriptionBundle\EventListener\StripeSubscriptionListener:
        tags: ['kernel.event_subscriber']