services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $apiSecretKey: '%sfs_platform.stripe.secret_key%'
            $webhookSigningSecret: '%sfs_customer.adapter.stripe.webhookSigningSecret%'
            $logger: '@?monolog.logger.stripe'

    Softspring\SubscriptionBundle\Platform\Adapter\SubscriptionAdapterInterface:
        class: Softspring\PlatformBundle\Stripe\Adapter\SubscriptionAdapter
        calls:
            - ['setItemManager', ['@Softspring\SubscriptionBundle\Manager\SubscriptionItemManagerInterface']]
            - ['setPlanManager', ['@Softspring\SubscriptionBundle\Manager\PlanManagerInterface']]
        tags:
          - { name: 'sfs_platform.adapter', alias: 'subscription' }

    Softspring\SubscriptionBundle\Platform\Adapter\PlanAdapterInterface:
        class: Softspring\PlatformBundle\Stripe\Adapter\PlanAdapter
        tags:
          - { name: 'sfs_platform.adapter', alias: 'plan' }

    Softspring\SubscriptionBundle\Platform\Adapter\ProductAdapterInterface:
        class: Softspring\PlatformBundle\Stripe\Adapter\ProductAdapter
        tags:
          - { name: 'sfs_platform.adapter', alias: 'product' }

    Softspring\SubscriptionBundle\EventListener\StripeSubscriptionListener:
        tags: ['kernel.event_subscriber']

    Softspring\SubscriptionBundle\EventListener\StripeSubscriptionsNotifyListener:
        tags: ['kernel.event_subscriber']