services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $apiSecretKey: '%sfs_customer.adapter.stripe.apiSecretKey%'
            $webhookSigningSecret: '%sfs_customer.adapter.stripe.webhookSigningSecret%'

    Softspring\SubscriptionBundle\Adapter\SubscriptionAdapterInterface:
        class: Softspring\SubscriptionBundle\Adapter\Stripe\StripeSubscriptionAdapter
        tags:
          - { name: 'sfs_customer.platform.adapter', alias: 'subscription' }

    Softspring\SubscriptionBundle\Adapter\PlanAdapterInterface:
        class: Softspring\SubscriptionBundle\Adapter\Stripe\StripePlanAdapter
        tags:
          - { name: 'sfs_customer.platform.adapter', alias: 'plan' }

    Softspring\SubscriptionBundle\EventListener\StripeSubscriptionListener:
        tags: ['kernel.event_subscriber']

    Softspring\SubscriptionBundle\EventListener\StripeNotifyListener:
        tags: ['kernel.event_subscriber']

    Softspring\SubscriptionBundle\EventListener\StripeAdminSubscriptionListener:
        tags: ['kernel.event_subscriber']