services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $em: '@sfs_subscription.entity_manager'
            $api: '@Softspring\CustomerBundle\Manager\ApiManagerInterface'

    Softspring\SubscriptionBundle\Controller\:
        resource: '../../../Controller/*'
        public: true

    Softspring\SubscriptionBundle\Form\:
        resource: '../../../Form/*'

    Softspring\SubscriptionBundle\Manager\:
        resource: '../../../Manager/*'

    Softspring\SubscriptionBundle\Entity\EntityListener\StoreSubscriptionTransitionsListener:
        tags:
            - { name: 'doctrine.orm.entity_listener', event: 'postLoad', entity: 'Softspring\SubscriptionBundle\Model\Subscription', lazy: true }
            - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'Softspring\SubscriptionBundle\Model\Subscription', lazy: true }
            - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'Softspring\SubscriptionBundle\Model\Subscription', lazy: true }

    Softspring\SubscriptionBundle\Request\ParamConverter\:
        resource: '../../../Request/ParamConverter/*'
        tags: ['request.param_converter']