services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $em: '@sfs_subscription.entity_manager'
            $api: '@Softspring\CustomerBundle\Manager\ApiManagerInterface'

    Softspring\SubscriptionBundle\Controller\:
        resource: '../../../Controller/*'
        public: true

    Softspring\SubscriptionBundle\Form\:
        resource: '../../../Form/*'

    Softspring\SubscriptionBundle\Manager\:
        resource: '../../../Manager/*'

    Softspring\SubscriptionBundle\Request\ParamConverter\:
        resource: '../../../Request/ParamConverter/*'
        tags: ['request.param_converter']