services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $em: '@sfs_subscription.entity_manager'

    Softspring\SubscriptionBundle\Controller\:
        resource: '../../../Controller/*'
        public: true

    Softspring\SubscriptionBundle\Form\:
        resource: '../../../Form/*'

    Softspring\SubscriptionBundle\Manager\PlanManager: ~
    Softspring\SubscriptionBundle\Manager\ProductManager: ~
    Softspring\SubscriptionBundle\Manager\SubscriptionManager: ~

    Softspring\SubscriptionBundle\Manager\PlanManagerInterface:
        alias: 'Softspring\SubscriptionBundle\Manager\PlanManager'

    Softspring\SubscriptionBundle\Manager\ProductManagerInterface:
        alias: 'Softspring\SubscriptionBundle\Manager\ProductManager'

    Softspring\SubscriptionBundle\Manager\SubscriptionManagerInterface:
        alias: 'Softspring\SubscriptionBundle\Manager\SubscriptionManager'
