security:
    role_hierarchy:
        ROLE_SUBSCRIPTION_ADMIN_SUBSCRIPTIONS:
            - ROLE_SUBSCRIPTION_ADMIN_SUBSCRIPTION_LIST
            - ROLE_SUBSCRIPTION_ADMIN_SUBSCRIPTION_DETAILS
            - ROLE_SUBSCRIPTION_ADMIN_SUBSCRIPTIONS_SYNC
            - ROLE_SUBSCRIPTION_ADMIN_SUBSCRIPTIONS_CANCEL_RENOVATION
            - ROLE_SUBSCRIPTION_ADMIN_SUBSCRIPTIONS_UNCANCEL_RENOVATION
            - ROLE_SUBSCRIPTION_ADMIN_SUBSCRIPTIONS_CANCEL_NOW
        ROLE_SUBSCRIPTION_ADMIN_PLANS:
            - ROLE_SUBSCRIPTION_ADMIN_PLANS_LIST
            - ROLE_SUBSCRIPTION_ADMIN_PLANS_SYNC_ALL
        ROLE_SUBSCRIPTION_ADMIN_PRODUCTS:
            - ROLE_SUBSCRIPTION_ADMIN_PRODUCTS_LIST
            - ROLE_SUBSCRIPTION_ADMIN_PRODUCTS_SYNC_ALL
