sfs_subscription_admin_plans_list:
    controller: sfs_subscription.admin.plan.controller::list
    path: /

sfs_subscription_admin_plans_create:
    controller: sfs_subscription.admin.plan.controller::create
    path: /create

sfs_subscription_admin_plans_sync_all:
    controller: Softspring\SubscriptionBundle\Controller\Admin\PlanController::syncAll
    path: /sync-all
