sfs_subscription_admin_subscriptions_list:
    controller: sfs_subscription.admin.subscription.controller::list
    path: /

sfs_subscription_admin_subscriptions_read:
    controller: sfs_subscription.admin.subscription.controller::read
    path: /{entity}