sfs_subscription_subscribe_choose_plan:
    controller: sfs_subscription.subscribe.controller::choosePlan
    path: /choose-a-plan

sfs_subscription_subscribe:
    controller: sfs_subscription.subscribe.controller::subscribe
    path: /subscribe/{plan}

sfs_subscription_subscribe_trial:
    controller: sfs_subscription.subscribe.controller::trial
    path: /subscribe/{plan}/trial

sfs_subscription_subscribe_add_card:
    controller: sfs_subscription.subscribe.controller::addStripeCard
    path: /subscribe/{plan}/add-card

