services:
    sfs_subscription.account.subscription.controller:
        class: Softspring\SubscriptionBundle\Controller\Account\SubscriptionController
        public: true
        arguments:
            $subscriptionManager: '@Softspring\SubscriptionBundle\Manager\SubscriptionManagerInterface'
            $planManager: '@Softspring\SubscriptionBundle\Manager\PlanManagerInterface'
            $eventDispatcher: '@event_dispatcher'
            $em: '@sfs_subscription.entity_manager'
            $clientAdapter: '@Softspring\SubscriptionBundle\Adapter\CustomerAdapterInterface'

