services:
    Softspring\SubscriptionBundle\Form\Admin\CustomerListFilterFormInterface:
        alias: 'Softspring\SubscriptionBundle\Form\Admin\CustomerListFilterForm'

    sfs_subscription.admin.customer.controller:
        class: Softspring\AdminBundle\Controller\EntityController
        public: true
        calls:
            - { method: setContainer, arguments: ['@service_container'] }
        arguments:
            $manager: '@Softspring\SubscriptionBundle\Manager\CustomerManagerInterface'
            $eventDispatcher: '@event_dispatcher'
            $listFilterForm: '@Softspring\SubscriptionBundle\Form\Admin\CustomerListFilterFormInterface'
            $createForm: null
            $updateForm: null
            $deleteForm: null
            $config:
                list:
                    view_event_name: !php/const Softspring\SubscriptionBundle\SfsSubscriptionEvents::ADMIN_CUSTOMERS_LIST_VIEW
                    view: '@@SfsSubscription/admin/customer/list.html.twig'
                    view_page: '@@SfsSubscription/admin/customer/list-page.html.twig'
