services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Softspring\SubscriptionBundle\Controller\Admin\PlanController:
        public: true
        tags: ['controller.service_arguments']

    Softspring\SubscriptionBundle\Form\Admin\PlanListFilterFormInterface:
        class: 'Softspring\SubscriptionBundle\Form\Admin\PlanListFilterForm'

    Softspring\SubscriptionBundle\Form\Admin\PlanCreateFormInterface:
        class: 'Softspring\SubscriptionBundle\Form\Admin\PlanCreateForm'

    Softspring\SubscriptionBundle\Form\Admin\PlanUpdateFormInterface:
        class: 'Softspring\SubscriptionBundle\Form\Admin\PlanUpdateForm'

    sfs_subscription.admin.plan.controller:
        class: Softspring\CrudlBundle\Controller\CrudlController
        public: true
        calls:
            - { method: setContainer, arguments: ['@service_container'] }
        arguments:
            $manager: '@Softspring\SubscriptionBundle\Manager\PlanManagerInterface'
            $listFilterForm: '@Softspring\SubscriptionBundle\Form\Admin\PlanListFilterFormInterface'
            $createForm: '@Softspring\SubscriptionBundle\Form\Admin\PlanCreateFormInterface'
            $updateForm: '@Softspring\SubscriptionBundle\Form\Admin\PlanUpdateFormInterface'
            $deleteForm: null
            $config:
                entity_attribute: 'plan'
                list:
                    is_granted: 'ROLE_SUBSCRIPTION_ADMIN_PLANS_LIST'
                    view_event_name: !php/const Softspring\SubscriptionBundle\SfsSubscriptionEvents::ADMIN_PLANS_LIST_VIEW
                    view: '@@SfsSubscription/admin/plan/list.html.twig'
                    view_page: '@@SfsSubscription/admin/plan/list-page.html.twig'
                create:
                    is_granted: 'ROLE_SUBSCRIPTION_ADMIN_PLANS_CREATE'
                    initialize_event_name: !php/const Softspring\SubscriptionBundle\SfsSubscriptionEvents::ADMIN_PLANS_CREATE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\SubscriptionBundle\SfsSubscriptionEvents::ADMIN_PLANS_CREATE_FORM_VALID
                    success_event_name: !php/const Softspring\SubscriptionBundle\SfsSubscriptionEvents::ADMIN_PLANS_CREATE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\SubscriptionBundle\SfsSubscriptionEvents::ADMIN_PLANS_CREATE_FORM_INVALID
                    view_event_name: !php/const Softspring\SubscriptionBundle\SfsSubscriptionEvents::ADMIN_PLANS_CREATE_VIEW
                    view: '@@SfsSubscription/admin/plan/create.html.twig'
