parameters:
    sfs_subscription.admin.products.list_view: '@@SfsSubscription/admin/product/list.html.twig'
    sfs_subscription.admin.products.list_page_view: '@@SfsSubscription/admin/product/list-page.html.twig'
    sfs_subscription.admin.products.create_view: '@@SfsSubscription/admin/product/create.html.twig'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Softspring\SubscriptionBundle\Controller\Admin\ProductController:
        public: true
        tags: ['controller.service_arguments']

    Softspring\SubscriptionBundle\Form\Admin\ProductListFilterFormInterface:
        class: 'Softspring\SubscriptionBundle\Form\Admin\ProductListFilterForm'

    Softspring\SubscriptionBundle\Form\Admin\ProductCreateFormInterface:
        class: 'Softspring\SubscriptionBundle\Form\Admin\ProductCreateForm'

    Softspring\SubscriptionBundle\Form\Admin\ProductUpdateFormInterface:
        class: 'Softspring\SubscriptionBundle\Form\Admin\ProductUpdateForm'

    sfs_subscription.admin.product.controller:
        class: Softspring\CrudlBundle\Controller\CrudlController
        public: true
        calls:
            - { method: setContainer, arguments: ['@service_container'] }
        arguments:
            $manager: '@Softspring\SubscriptionBundle\Manager\ProductManagerInterface'
            $listFilterForm: '@Softspring\SubscriptionBundle\Form\Admin\ProductListFilterFormInterface'
            $createForm: '@Softspring\SubscriptionBundle\Form\Admin\ProductCreateFormInterface'
            $updateForm: '@Softspring\SubscriptionBundle\Form\Admin\ProductUpdateFormInterface'
            $deleteForm: null
            $config:
                entity_attribute: 'product'
                list:
                    is_granted: 'ROLE_SUBSCRIPTION_ADMIN_PRODUCTS_LIST'
                    view_event_name: !php/const Softspring\SubscriptionBundle\SfsSubscriptionEvents::ADMIN_PRODUCTS_LIST_VIEW
                    view: '%sfs_subscription.admin.products.list_view%'
                    view_page: '%sfs_subscription.admin.products.list_page_view%'
                create:
                    is_granted: 'ROLE_SUBSCRIPTION_ADMIN_PRODUCTS_CREATE'
                    initialize_event_name: !php/const Softspring\SubscriptionBundle\SfsSubscriptionEvents::ADMIN_PRODUCTS_CREATE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\SubscriptionBundle\SfsSubscriptionEvents::ADMIN_PRODUCTS_CREATE_FORM_VALID
                    success_event_name: !php/const Softspring\SubscriptionBundle\SfsSubscriptionEvents::ADMIN_PRODUCTS_CREATE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\SubscriptionBundle\SfsSubscriptionEvents::ADMIN_PRODUCTS_CREATE_FORM_INVALID
                    view_event_name: !php/const Softspring\SubscriptionBundle\SfsSubscriptionEvents::ADMIN_PRODUCTS_CREATE_VIEW
                    view: '%sfs_subscription.admin.products.create_view%'
