services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Softspring\SubscriptionBundle\Form\Admin\SubscriptionListFilterFormInterface:
        alias: 'Softspring\SubscriptionBundle\Form\Admin\SubscriptionListFilterForm'

    Softspring\SubscriptionBundle\Controller\Admin\SubscriptionController:
        public: true
        calls:
            - { method: setContainer, arguments: ['@service_container'] }

    sfs_subscription.admin.subscription.controller:
        class: Softspring\CrudlBundle\Controller\CrudlController
        public: true
        calls:
            - { method: setContainer, arguments: ['@service_container'] }
        arguments:
            $manager: '@Softspring\SubscriptionBundle\Manager\SubscriptionManagerInterface'
            $listFilterForm: '@Softspring\SubscriptionBundle\Form\Admin\SubscriptionListFilterFormInterface'
            $createForm: null
            $updateForm: null
            $deleteForm: null
            $config:
                entity_attribute: 'subscription'
                list:
                    is_granted: 'ROLE_SUBSCRIPTION_ADMIN_SUBSCRIPTION_LIST'
                    filter_event_name: !php/const Softspring\SubscriptionBundle\SfsSubscriptionEvents::ADMIN_SUBSCRIPTIONS_LIST_FILTER
                    view_event_name: !php/const Softspring\SubscriptionBundle\SfsSubscriptionEvents::ADMIN_SUBSCRIPTIONS_LIST_VIEW
                    view: '@@SfsSubscription/admin/subscription/list.html.twig'
                    view_page: '@@SfsSubscription/admin/subscription/list-page.html.twig'
                    read_route: 'sfs_subscription_admin_subscriptions_read'
                read:
                    is_granted: 'ROLE_SUBSCRIPTION_ADMIN_SUBSCRIPTION_DETAILS'
                    param_converter_key: 'id'
                    view_event_name: !php/const Softspring\SubscriptionBundle\SfsSubscriptionEvents::ADMIN_SUBSCRIPTIONS_READ_VIEW
                    view: '@@SfsSubscription/admin/subscription/read.html.twig'