services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $em: '@sfs_subscription.entity_manager'

    Softspring\SubscriptionBundle\Manager\PlanManagerInterface:
        class: Softspring\SubscriptionBundle\Manager\PlanManager
        calls:
            - ['setAdapterManager', ['@Softspring\PlatformBundle\Manager\AdapterManagerInterface']]
            - ['setPlatformProvider', ['@Softspring\PlatformBundle\Provider\PlatformProviderInterface']]

    Softspring\SubscriptionBundle\Command\SyncAllPlansCommand:
        tags: ['console.command']