services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $em: '@sfs_subscription.entity_manager'
            $api: '@Softspring\CustomerBundle\Platform\ApiManagerInterface'

    Softspring\SubscriptionBundle\Manager\PlanManagerInterface:
        class: Softspring\SubscriptionBundle\Manager\PlanManager