services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $em: '@sfs_subscription.entity_manager'

    Softspring\SubscriptionBundle\Manager\SubscriptionItemManagerInterface:
        class: Softspring\SubscriptionBundle\Manager\SubscriptionItemManager
        arguments:
            $targetClass: 'Softspring\SubscriptionBundle\Model\SubscriptionItemInterface'

    Softspring\SubscriptionBundle\Manager\SubscriptionManagerInterface:
        class: Softspring\SubscriptionBundle\Manager\SubscriptionManager
        arguments:
            $itemManager: '@Softspring\SubscriptionBundle\Manager\SubscriptionItemManagerInterface'